// Generates meditation narration for the last 7 languages: es, fr, de, pt,
// pl, sv, sw. Run with:
//   node --env-file=scripts/audio/.env scripts/audio/generate-final.mjs

import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'

const API_KEY = process.env.INWORLD_API_KEY
if (!API_KEY) {
  console.error('Missing INWORLD_API_KEY. Put it in scripts/audio/.env (see .env.example).')
  process.exit(1)
}

const VOICE_ID = 'dancing-comet-7283__boyan_venkov'
const MODEL_ID = 'inworld-tts-2'
const OUT_ROOT = path.join(import.meta.dirname, '..', '..', 'public', 'audio', 'meditations')

const LOCALES = ['sw', 'sv', 'pl', 'pt', 'es', 'de', 'fr']
const LANG_CODES = { es: 'es-ES', fr: 'fr-FR', de: 'de-DE', pt: 'pt-BR', pl: 'pl-PL', sv: 'sv-SE', sw: 'sw-KE' }

const LINES = {
  sw: {
    'med.step.settle': 'Macho yamefungwa. Acha mwili utulie na pumzi ipunguze kasi yenyewe.',
    'med.step.breath': 'Weka uangalifu kwenye pumzi — ifuate ikiingia, ifuate ikitoka. Akili inapotanga-tanga, kutambua huko ndiko zoezi. Rudi, kwa upole.',
    'med.step.close': 'Acha zoezi liende. Tambua unavyohisi sasa, kabla ya kufungua macho.',
    'med.step.ba.count': 'Sasa hesabu kila kutoa pumzi — moja hadi kumi, kisha anza upya. Ukipoteza hesabu, anza tu kutoka moja. Hakuna anayeweka alama.',
    'med.step.scan.0': 'Fagia uangalifu polepole kutoka nyayo za miguu kwenda juu — vifundo, miguu, nyonga, tumbo, mgongo, kifua, mikono, viganja. Pumzika pumzi chache pale unapokutana na msongo, na uache ulege.',
    'med.step.scan.1': 'Sasa mabega, koo, taya, nafasi kuzunguka macho, ngozi ya kichwa. Kisha hisi mwili mzima kwa mara moja — mzito, wa joto, ukipumua wenyewe.',
    'med.step.metta.0': 'Jilete akilini, kama ulivyo leo hasa. Kimya toa: na niwe salama, na niwe mzima, na niwe na amani. Rudia polepole na jiruhusu kumaanisha kweli.',
    'med.step.metta.1': 'Lete akilini mtu unayempenda kwa urahisi. Fikiria uso wake na toa vilevile: na uwe salama, na uwe mzima, na uwe na amani.',
    'med.step.metta.2': 'Sasa ipanue — mtu usiyemjua vizuri, mtu unayemwona mgumu, kisha wote, kila mahali: viumbe vyote na viwe salama, viumbe vyote na viwe na amani.',
    'med.step.bath.0': 'Acha sauti ije mbele ya uangalifu. Husikilizi kwa juhudi — unaacha sauti ifike, kama nuru inavyofika.',
    'med.step.bath.1': 'Tambua sauti inaonekana kutua wapi mwilini — kifuani, fuvuni, mikononi. Acha nafasi kati yako na sauti iyeyuke.',
    'med.step.grat.0': 'Lete akilini kitu kimoja kutoka siku iliyopita kilichokwenda vizuri, hata kidogo kiasi gani. Usikitaje tu — hisi pale shukrani inapokaa mwilini.',
    'med.step.grat.1': 'Sasa kitu ambacho kwa kawaida unachukulia kuwa cha kawaida — mwili unaofanya kazi, paa, mtu aliyebaki. Baki nacho pumzi chache.',
    'med.step.grat.2': 'Kimoja zaidi — kuhusu wewe mwenyewe. Namna ulivyosimama, jambo ulilolishughulikia, juhudi ambayo hakuna aliyeiona. Shikilia vyote vitatu pamoja.',
    'med.step.safe.0': 'Fikiria mahali unapohisi salama kabisa — halisi au pa kufikirika. Angalia polepole: nuru, saa ya siku, unachosikia, unachohisi kwenye ngozi.',
    'med.step.safe.1': 'Pata mahali hapa ambapo ungependa zaidi kupumzika, na uende huko. Hakuna kinachotakiwa kwako. Hakuna kinachokufikia usichokiruhusu.',
    'med.step.mtn.0': 'Fikiria mlima — msingi wake mpana, kando zake imara, kilele chake kilichotulia. Acha mwili wako na mlima viwe umbo moja: kiti ni msingi, uti wa mgongo ni mteremko, kichwa ni kilele.',
    'med.step.mtn.1': 'Hali ya hewa inakuja na kuondoka kuzunguka mlima — nuru, wingu, upepo, dhoruba. Mawazo na hali zako za moyo ni hali ya hewa. Mlima haubishani nayo, wala haupungui kwa sababu yake.',
    'med.step.open.0': 'Achilia nanga ya pumzi. Acha uangalifu uwe wazi pana, si juu ya kitu chochote hasa. Sauti, hisia, mawazo huinuka na kupita — huyafuatilii wala kuyasukuma mbali.',
    'med.step.open.1': 'Tambua kwamba utambuzi wenyewe hausogei. Mambo yanatokea ndani yake, kama mawingu yanavyotokea ndani ya anga. Pumzika kama anga hilo — hakuna cha kuongeza, hakuna cha kuondoa.',
    'med.step.morn.0': 'Pumzi tatu zilizojaa zaidi, za kina kidogo kuliko kawaida — ziache ziuamshe mwili kutoka ndani. Zungusha mabega nyuma mara moja na uhisi mbele ya mwili ikifunguka.',
    'med.step.morn.1': 'Lete siku ijayo akilini kwa wepesi, kisha chagua nia moja — si kazi, bali namna ya kuwa. Mwenye subira. Mwaminifu. Jasiri. Mwema. Iseme mara moja: leo, nitakuwa ___.',
    'med.step.eve.0': 'Acha siku ipite kwa wepesi, kama mandhari kutoka dirisha la treni — asubuhi, adhuhuri, jioni. Usisimame pahali popote. Kama kipande fulani kinakuvuta, kiandike na useme: si sasa.',
    'med.step.eve.1': 'Pata kipande kimoja unachofurahi kwamba kilitokea, na jambo moja ulilofanya vizuri kadri ulivyoweza, kwa jinsi siku ilivyokwenda kweli. Acha hilo litoshe. Sasa acha siku nzima iende — imekamilika kwa sababu tu imeisha.',
    'med.step.nidra.0': 'Lala bila kusonga kabisa — kimya zaidi ya kinachohisi asili, ni pumzi tu inayosogea. Weka nia fupi, sentensi moja tulivu ya wakati uliopo. Iseme moyoni mara tatu.',
    'med.step.nidra.1': 'Leta uangalifu kwa kila pahali kadri linavyotajwa, bila kusonga — mkono wa kulia: kidole gumba, vidole, kiganja, kifundo cha mkono, kigasha, kiwiko, bega. Kisha vivyo hivyo kushoto.',
    'med.step.nidra.2': 'Nyonga zote mbili. Mguu wa kulia — paja, goti, muundi, kifundo cha mguu, wayo, vidole. Mguu wa kushoto vilevile. Mgongo mzima juu ya sakafu, tumbo likipanda na kushuka, kifua, koo.',
    'med.step.nidra.3': 'Uso — taya, midomo, pua, mashavu, macho, nafasi kati ya nyusi, ngozi nzima ya kichwa. Sasa mwili mzima kwa mara moja, ukimeta hafifu, ukishikiliwa na sakafu. Rudi kwenye nia yako.',
    'med.step.chakra.root.0': 'Peleka uangalifu wako kwenye msingi wa uti wa mgongo, ambapo unakutana na ardhi. Huu ni kitovu chako cha mizizi — kinabeba hisia yako ya usalama, ya kuwa na cha kutosha, ya kuruhusiwa kuwepo tu hapa. Kama leo imehisi kuyumba, uthabiti huo unaanzia hapa hapa.',
    'med.step.chakra.root.1': 'Pumua kana kwamba pumzi yenyewe inafika chini kabisa. Kimya, kwa mdundo wa pumzi: Niko salama. Niko hapa. Nina kile ninachohitaji.',
    'med.step.chakra.sacral.0': 'Peleka uangalifu wako kwenye tumbo la chini, upana wa kiganja chini ya kitovu. Huu ni kitovu chako cha sakrali — kinabeba uwezo wako wa kuhisi, kufurahia, kuruhusu maisha yasogee badala ya kuganda mbele yake.',
    'med.step.chakra.sacral.1': 'Ruhusu pumzi ilainishe nafasi hii badala ya kuikaza. Kimya, kwa mdundo wa pumzi: Naacha maisha yasogee ndani yangu.',
    'med.step.chakra.solar-plexus.0': 'Peleka uangalifu wako kwenye sehemu laini chini ya mbavu. Huu ni mfumo wako wa jua — moto wako, dhamira yako, sehemu yako inayoamua na kutenda badala ya kujikunja.',
    'med.step.chakra.solar-plexus.1': 'Ruhusu pumzi iuchochee kwa upole, bila kulazimisha. Kimya, kwa mdundo wa pumzi: Naamini moto wangu.',
    'med.step.chakra.heart.0': 'Peleka uangalifu wako katikati ya kifua. Huu ni kitovu chako cha moyo — kinachokuruhusu kutoa bila kujipoteza, na kupokea bila kujilinda.',
    'med.step.chakra.heart.1': 'Ruhusu pumzi ipanue nafasi hii, mbele na nyuma. Kimya, kwa mdundo wa pumzi: Natoa na kupokea upendo kwa uhuru.',
    'med.step.chakra.throat.0': 'Peleka uangalifu wako kwenye shimo la koo. Hii ni sauti yako — inayokuruhusu kusema jambo la kweli badala ya jepesi.',
    'med.step.chakra.throat.1': 'Ruhusu pumzi ipite hapa bila kizuizi. Kimya, kwa mdundo wa pumzi: Nasema kweli yangu kwa urahisi.',
    'med.step.chakra.third-eye.0': 'Peleka uangalifu wako kwenye nafasi kati ya nyusi. Hapa ndipo unahisi kile unachojua kabla ya kukieleza.',
    'med.step.chakra.third-eye.1': 'Ruhusu pumzi itulize kelele ili maarifa hayo tulivu zaidi yasikike. Kimya, kwa mdundo wa pumzi: Naamini kile ninachokiona ndani.',
    'med.step.chakra.crown.0': 'Peleka uangalifu wako kwenye utosi wa kichwa, na kidogo juu yake. Hapa ndipo unaungana na kitu kikubwa kuliko mahangaiko ya leo.',
    'med.step.chakra.crown.1': 'Ruhusu pumzi ipande kwa upole kupitia mwili wote kukutana nacho. Kimya, kwa mdundo wa pumzi: Ni sehemu ya kitu kikubwa, na kinanibeba.',
  },
  sv: {
    'med.step.settle': 'Ögonen slutna. Låt kroppen sätta sig och andningen sakta av av sig själv.',
    'med.step.breath': 'Vila uppmärksamheten på andningen — följ den in, följ den ut. När sinnet vandrar är det märkandet praktiken. Kom tillbaka, mjukt.',
    'med.step.close': 'Släpp praktiken. Lägg märke till hur du känner dig nu, innan du öppnar ögonen.',
    'med.step.ba.count': 'Räkna nu varje utandning — ett till tio, börja sedan om. Tappar du räkningen, börja bara på ett igen. Ingen håller poäng.',
    'med.step.scan.0': 'Svep uppmärksamheten långsamt från fotsulorna och uppåt — vrister, ben, höfter, mage, rygg, bröst, armar, händer. Vila några andetag där du möter spänning, och låt den mjukna.',
    'med.step.scan.1': 'Nu axlarna, halsen, käken, rummet runt ögonen, hårbotten. Känn sedan hela kroppen på en gång — tung, varm, andas av sig själv.',
    'med.step.metta.0': 'För fram dig själv i sinnet, precis som du är idag. Erbjud tyst: må jag vara trygg, må jag må väl, må jag vara i frid. Upprepa det långsamt och tillåt dig att verkligen mena det.',
    'med.step.metta.1': 'För fram någon du älskar lätt. Se ansiktet framför dig och erbjud detsamma: må du vara trygg, må du må väl, må du vara i frid.',
    'med.step.metta.2': 'Vidga det nu — någon du knappt känner, någon du finner svår, sedan alla, överallt: må alla varelser vara trygga, må alla varelser vara i frid.',
    'med.step.bath.0': 'Låt tonen komma i förgrunden. Du lyssnar inte ansträngt — du låter ljudet komma, så som ljus kommer.',
    'med.step.bath.1': 'Lägg märke till var i kroppen ljudet tycks landa — bröstet, skallen, händerna. Låt rummet mellan dig och ljudet lösas upp.',
    'med.step.grat.0': 'För fram en sak från det senaste dygnet som gick bra, hur liten den än var. Nöj dig inte med att namnge den — känn var tacksamheten sätter sig i kroppen.',
    'med.step.grat.1': 'Nu något du brukar ta för givet — en fungerande kropp, ett tak, någon som stannade. Stanna kvar några andetag.',
    'med.step.grat.2': 'En till — något om dig själv. Ett sätt du var närvarande på, en sak du hanterade, en möda ingen såg. Håll alla tre samtidigt.',
    'med.step.safe.0': 'Föreställ dig en plats där du känner dig helt trygg — verklig eller påhittad. Se dig omkring långsamt: ljuset, tiden på dygnet, vad du hör, vad du känner mot huden.',
    'med.step.safe.1': 'Hitta stället här där du helst skulle vilja vila, och gå dit. Inget krävs av dig. Inget når dig som du inte tillåter.',
    'med.step.mtn.0': 'Föreställ dig ett berg — dess breda bas, dess fasta sidor, dess stilla topp. Låt din kropp och berget bli samma form: sätet som bas, ryggraden som sluttning, huvudet som topp.',
    'med.step.mtn.1': 'Vädret kommer och går runt berget — ljus, moln, vind, storm. Dina tankar och stämningar är vädret. Berget bråkar inte med det, och blir inte mindre av det.',
    'med.step.open.0': 'Släpp andningens ankare. Låt uppmärksamheten vara vidöppen, inte på något särskilt. Ljud, förnimmelser, tankar uppstår och passerar — du varken jagar dem eller skjuter bort dem.',
    'med.step.open.1': 'Lägg märke till att medvetenheten själv inte rör sig. Saker sker inom den, så som moln sker inom himlen. Vila som den himlen — inget att lägga till, inget att ta bort.',
    'med.step.morn.0': 'Tre fylligare andetag, lite djupare än vanligt — låt dem väcka kroppen inifrån. Rulla axlarna bakåt en gång och känn kroppens framsida öppna sig.',
    'med.step.morn.1': 'För dagen som kommer löst i sinnet, välj sedan en avsikt — inte en uppgift, ett sätt att vara. Tålmodig. Ärlig. Modig. Vänlig. Säg det en gång: idag ska jag vara ___.',
    'med.step.eve.0': 'Låt dagen spelas upp lätt, som landskap från ett tågfönster — morgon, middag, kväll. Stanna inte på något. Om ett ögonblick drar, notera det och säg: inte nu.',
    'med.step.eve.1': 'Hitta ett ögonblick du är glad att det hände, och en sak du gjorde så bra du kunde. Låt det räcka. Släpp nu hela dagen — den är fullbordad helt enkelt för att den är över.',
    'med.step.nidra.0': 'Ligg helt stilla — stillare än vad som känns naturligt, bara andningen rör sig. Sätt en kort avsikt, en enda lugn mening i presens. Säg den inombords tre gånger.',
    'med.step.nidra.1': 'För uppmärksamheten till varje plats allteftersom den nämns, utan att röra dig — höger hand: tumme, fingrar, handflata, handled, underarm, armbåge, axel. Sedan detsamma till vänster.',
    'med.step.nidra.2': 'Båda höfterna. Höger ben — lår, knä, smalben, vrist, fot, tår. Vänster ben likadant. Hela ryggen mot golvet, magen som höjs och sänks, bröstet, halsen.',
    'med.step.nidra.3': 'Ansiktet — käke, läppar, näsa, kinder, ögon, rummet mellan ögonbrynen, hårbotten. Nu hela kroppen på en gång, svagt lysande, buren av golvet. Återvänd till din avsikt.',
    'med.step.chakra.root.0': 'För din uppmärksamhet till ryggradens bas, där du möter marken. Det här är ditt rotcentrum — det bär din känsla av trygghet, av att ha nog, av att få lov att bara vara här. Om dagen har känts skakig börjar den stadgan just här.',
    'med.step.chakra.root.1': 'Andas som om andningen själv nådde hela vägen ner. Tyst, i takt med andningen: Jag är trygg. Jag är här. Jag har det jag behöver.',
    'med.step.chakra.sacral.0': 'För din uppmärksamhet till nedre magen, en handsbredd under naveln. Det här är ditt sakralcentrum — det bär din förmåga att känna, att njuta, att låta livet röra sig istället för att stelna inför det.',
    'med.step.chakra.sacral.1': 'Låt andningen mjuka upp det här utrymmet istället för att spänna det. Tyst, i takt med andningen: Jag låter livet röra sig genom mig.',
    'med.step.chakra.solar-plexus.0': 'För din uppmärksamhet till den mjuka punkten under revbenen. Det här är din solarplexus — din eld, din vilja, den del av dig som bestämmer och handlar istället för att dra sig undan.',
    'med.step.chakra.solar-plexus.1': 'Låt andningen fläkta den försiktigt, utan att tvinga. Tyst, i takt med andningen: Jag litar på min eld.',
    'med.step.chakra.heart.0': 'För din uppmärksamhet till bröstets mitt. Det här är ditt hjärtcentrum — det som låter dig ge utan att förlora dig själv, och ta emot utan att skydda dig.',
    'med.step.chakra.heart.1': 'Låt andningen vidga det här utrymmet, fram och bak. Tyst, i takt med andningen: Jag ger och tar emot kärlek fritt.',
    'med.step.chakra.throat.0': 'För din uppmärksamhet till halsgropen. Det här är din röst — den som låter dig säga det sanna istället för det enkla.',
    'med.step.chakra.throat.1': 'Låt andningen röra sig obehindrat härigenom. Tyst, i takt med andningen: Jag säger min sanning med lätthet.',
    'med.step.chakra.third-eye.0': 'För din uppmärksamhet till rummet mellan ögonbrynen. Här känner du det du vet innan du kan förklara det.',
    'med.step.chakra.third-eye.1': 'Låt andningen lägga sig över bruset så att den tystare kunskapen kan höras. Tyst, i takt med andningen: Jag litar på det jag ser inombords.',
    'med.step.chakra.crown.0': 'För din uppmärksamhet till hjässan, och en bit ovanför. Här knyter du an till något större än dagens bekymmer.',
    'med.step.chakra.crown.1': 'Låt andningen stiga mjukt genom hela kroppen för att nå dit. Tyst, i takt med andningen: Jag är en del av något vidsträckt, och det bär mig.',
  },
  pl: {
    'med.step.settle': 'Oczy zamknięte. Niech ciało się osadzi, a oddech samo zwolni.',
    'med.step.breath': 'Oprzyj uwagę na oddechu — podążaj za nim do wewnątrz, podążaj na zewnątrz. Gdy umysł błądzi, to zauważanie jest praktyką. Wróć, łagodnie.',
    'med.step.close': 'Puść praktykę. Zauważ, jak się teraz czujesz, zanim otworzysz oczy.',
    'med.step.ba.count': 'Teraz licz każdy wydech — od jednego do dziesięciu, potem zacznij od nowa. Zgubisz rachubę — po prostu zacznij od jednego. Nikt nie liczy punktów.',
    'med.step.scan.0': 'Przesuwaj uwagę powoli od podeszew stóp w górę — kostki, nogi, biodra, brzuch, plecy, klatka, ramiona, dłonie. Spocznij kilka oddechów tam, gdzie spotykasz napięcie, i pozwól mu zmięknąć.',
    'med.step.scan.1': 'Teraz barki, gardło, szczęka, przestrzeń wokół oczu, skóra głowy. Potem poczuj całe ciało naraz — ciężkie, ciepłe, oddychające samo.',
    'med.step.metta.0': 'Przywołaj siebie w myślach, dokładnie takiego, jaki jesteś dzisiaj. Ofiaruj bezgłośnie: obym był bezpieczny, obym miał się dobrze, obym był w spokoju. Powtarzaj powoli i pozwól sobie naprawdę to mieć na myśli.',
    'med.step.metta.1': 'Przywołaj kogoś, kogo łatwo kochasz. Wyobraź jego twarz i ofiaruj to samo: obyś był bezpieczny, obyś miał się dobrze, obyś był w spokoju.',
    'med.step.metta.2': 'Teraz rozszerz to — ktoś, kogo ledwie znasz, ktoś, kogo uważasz za trudnego, potem wszyscy, wszędzie: oby wszystkie istoty były bezpieczne, oby wszystkie istoty były w spokoju.',
    'med.step.bath.0': 'Niech ton wyjdzie na pierwszy plan uwagi. Nie słuchasz z wysiłkiem — pozwalasz dźwiękowi przybyć, tak jak przybywa światło.',
    'med.step.bath.1': 'Zauważ, gdzie w ciele dźwięk zdaje się lądować — klatka, czaszka, dłonie. Niech przestrzeń między tobą a dźwiękiem się rozpuści.',
    'med.step.grat.0': 'Przywołaj jedną rzecz z ostatniego dnia, która poszła dobrze, choćby najmniejszą. Nie tylko ją nazwij — poczuj, gdzie wdzięczność osiada w ciele.',
    'med.step.grat.1': 'Teraz coś, co zwykle bierzesz za pewnik — działające ciało, dach, ktoś, kto został. Zostań z tym kilka oddechów.',
    'med.step.grat.2': 'Jeszcze jedna — coś o tobie. Sposób, w jaki się pokazałeś, rzecz, którą ogarnąłeś, wysiłek, którego nikt nie widział. Trzymaj wszystkie trzy razem.',
    'med.step.safe.0': 'Wyobraź miejsce, gdzie czujesz się całkowicie bezpiecznie — realne lub wyobrażone. Rozejrzyj się powoli: światło, pora dnia, co słyszysz, co czujesz na skórze.',
    'med.step.safe.1': 'Znajdź tu miejsce, gdzie najbardziej chciałbyś spocząć, i tam idź. Nic nie jest od ciebie wymagane. Nic cię nie dosięga, na co nie pozwolisz.',
    'med.step.mtn.0': 'Wyobraź górę — jej szeroka podstawa, jej solidne zbocza, jej nieruchomy szczyt. Niech twoje ciało i góra staną się tym samym kształtem: siedzisko to podstawa, kręgosłup to zbocze, głowa to szczyt.',
    'med.step.mtn.1': 'Pogoda przychodzi i odchodzi wokół góry — światło, chmura, wiatr, burza. Twoje myśli i nastroje to pogoda. Góra nie kłóci się z pogodą i nie staje się przez nią mniejsza.',
    'med.step.open.0': 'Puść kotwicę oddechu. Niech uwaga będzie szeroko otwarta, na niczym konkretnym. Dźwięki, doznania, myśli powstają i mijają — nie gonisz ich ani nie odpychasz.',
    'med.step.open.1': 'Zauważ, że sama świadomość się nie porusza. Rzeczy dzieją się w niej, tak jak chmury dzieją się w niebie. Spocznij jako to niebo — nic do dodania, nic do usunięcia.',
    'med.step.morn.0': 'Trzy pełniejsze oddechy, nieco głębsze niż zwykle — niech obudzą ciało od wewnątrz. Obróć raz barki do tyłu i poczuj, jak przód ciała się otwiera.',
    'med.step.morn.1': 'Przywołaj luźno nadchodzący dzień, potem wybierz jedną intencję — nie zadanie, sposób bycia. Cierpliwy. Szczery. Odważny. Życzliwy. Powiedz raz: dzisiaj będę ___.',
    'med.step.eve.0': 'Niech dzień przewinie się lekko, jak krajobraz z okna pociągu — poranek, południe, wieczór. Nie zatrzymuj się na niczym. Jeśli jakaś chwila ciągnie, zanotuj ją i powiedz: nie teraz.',
    'med.step.eve.1': 'Znajdź jedną chwilę, z której cieszysz się, że się wydarzyła, i jedną rzecz, którą zrobiłeś tak dobrze, jak mogłeś, biorąc pod uwagę, jak dzień faktycznie poszedł. Niech to wystarczy. Teraz puść cały dzień — jest kompletny po prostu dlatego, że się skończył.',
    'med.step.nidra.0': 'Połóż się całkiem nieruchomo — nieruchomiej, niż wydaje się naturalne, porusza się tylko oddech. Ustaw krótką intencję, jedno spokojne zdanie w czasie teraźniejszym. Powiedz je wewnętrznie trzy razy.',
    'med.step.nidra.1': 'Przynoś uwagę do każdego miejsca, gdy zostaje nazwane, bez ruchu — prawa dłoń: kciuk, palce, wnętrze dłoni, nadgarstek, przedramię, łokieć, bark. Potem to samo po lewej.',
    'med.step.nidra.2': 'Oba biodra. Prawa noga — udo, kolano, goleń, kostka, stopa, palce. Lewa noga tak samo. Całe plecy przy podłodze, brzuch wznoszący się i opadający, klatka, gardło.',
    'med.step.nidra.3': 'Twarz — szczęka, wargi, nos, policzki, oczy, przestrzeń między brwiami, skóra głowy. Teraz całe ciało naraz, świecące słabo, trzymane przez podłogę. Wróć do swojej intencji.',
    'med.step.chakra.root.0': 'Przenieś uwagę do podstawy kręgosłupa, tam gdzie spotykasz ziemię. To twój ośrodek korzenia — niesie twoje poczucie bezpieczeństwa, tego że masz dość, że wolno ci po prostu tu być. Jeśli dzisiaj było niepewnie, ta stabilność zaczyna się właśnie tutaj.',
    'med.step.chakra.root.1': 'Oddychaj tak, jakby sam oddech sięgał aż na sam dół. Bezgłośnie, w rytm oddechu: Czuję się bezpiecznie. Jestem tutaj. Mam to, czego potrzebuję.',
    'med.step.chakra.sacral.0': 'Przenieś uwagę do podbrzusza, szerokość dłoni pod pępkiem. To twój ośrodek sakralny — niesie twoją zdolność odczuwania, cieszenia się, pozwalania życiu płynąć zamiast zamierać wobec niego.',
    'med.step.chakra.sacral.1': 'Pozwól oddechowi zmiękczyć tę przestrzeń, zamiast ją ściskać. Bezgłośnie, w rytm oddechu: Pozwalam życiu poruszać się przeze mnie.',
    'med.step.chakra.solar-plexus.0': 'Przenieś uwagę do miękkiego miejsca pod żebrami. To twój splot słoneczny — twój ogień, twoja wola, ta część ciebie, która decyduje i działa zamiast się kurczyć.',
    'med.step.chakra.solar-plexus.1': 'Pozwól oddechowi delikatnie go rozniecać, bez forsowania. Bezgłośnie, w rytm oddechu: Ufam własnemu ogniowi.',
    'med.step.chakra.heart.0': 'Przenieś uwagę do środka klatki piersiowej. To twój ośrodek serca — dzięki niemu dajesz, nie tracąc siebie, i przyjmujesz, nie broniąc się.',
    'med.step.chakra.heart.1': 'Pozwól oddechowi rozszerzać tę przestrzeń, z przodu i z tyłu. Bezgłośnie, w rytm oddechu: Daję i przyjmuję miłość swobodnie.',
    'med.step.chakra.throat.0': 'Przenieś uwagę do wgłębienia gardła. To twój głos — dzięki niemu mówisz to, co prawdziwe, zamiast tego, co łatwe.',
    'med.step.chakra.throat.1': 'Pozwól oddechowi przepływać tędy bez przeszkód. Bezgłośnie, w rytm oddechu: Mówię swoją prawdę z łatwością.',
    'med.step.chakra.third-eye.0': 'Przenieś uwagę do przestrzeni między brwiami. Tu wyczuwasz to, co wiesz, zanim zdołasz to wyjaśnić.',
    'med.step.chakra.third-eye.1': 'Pozwól oddechowi uciszyć zgiełk, by dało się usłyszeć tę cichszą wiedzę. Bezgłośnie, w rytm oddechu: Ufam temu, co widzę w środku.',
    'med.step.chakra.crown.0': 'Przenieś uwagę na czubek głowy i trochę ponad nim. Tu łączysz się z czymś większym niż dzisiejsze troski.',
    'med.step.chakra.crown.1': 'Pozwól oddechowi unosić się łagodnie przez całe ciało, by to spotkać. Bezgłośnie, w rytm oddechu: Jestem częścią czegoś bezkresnego, a to mnie trzyma.',
  },
  pt: {
    'med.step.settle': 'Olhos fechados. Deixe o corpo assentar e a respiração desacelerar por conta própria.',
    'med.step.breath': 'Apoie a atenção na respiração — siga-a ao entrar, siga-a ao sair. Quando a mente vagar, esse perceber é a prática. Volte, com suavidade.',
    'med.step.close': 'Solte a prática. Note como você se sente agora, antes de abrir os olhos.',
    'med.step.ba.count': 'Agora conte cada expiração — de um a dez, depois recomece. Se perder a conta, simplesmente comece do um. Ninguém está marcando pontos.',
    'med.step.scan.0': 'Percorra a atenção lentamente das plantas dos pés para cima — tornozelos, pernas, quadris, ventre, costas, peito, braços, mãos. Descanse algumas respirações onde encontrar tensão, e deixe amolecer.',
    'med.step.scan.1': 'Agora os ombros, a garganta, a mandíbula, o espaço ao redor dos olhos, o couro cabeludo. Depois sinta o corpo inteiro de uma vez — pesado, quente, respirando sozinho.',
    'med.step.metta.0': 'Traga você mesmo à mente, exatamente como está hoje. Em silêncio ofereça: que eu esteja seguro, que eu esteja bem, que eu esteja em paz. Repita devagar e permita-se dizer de verdade.',
    'med.step.metta.1': 'Traga à mente alguém que você ama com facilidade. Imagine o rosto e ofereça o mesmo: que você esteja seguro, que você esteja bem, que você esteja em paz.',
    'med.step.metta.2': 'Agora amplie — alguém que você mal conhece, alguém que você acha difícil, depois todos, em todo lugar: que todos os seres estejam seguros, que todos os seres estejam em paz.',
    'med.step.bath.0': 'Deixe o tom vir para o primeiro plano. Você não escuta com esforço — deixa o som chegar, do jeito que a luz chega.',
    'med.step.bath.1': 'Note em que parte do corpo o som parece pousar — o peito, o crânio, as mãos. Deixe o espaço entre você e o som se dissolver.',
    'med.step.grat.0': 'Traga à mente uma coisa do último dia que foi bem, por menor que seja. Não apenas nomeie — sinta onde a gratidão se assenta no corpo.',
    'med.step.grat.1': 'Agora algo que você costuma considerar garantido — um corpo que funciona, um teto, alguém que ficou. Fique com isso algumas respirações.',
    'med.step.grat.2': 'Mais uma — algo sobre você. Um jeito como você se mostrou presente, algo que você lidou, um esforço que ninguém viu. Segure as três juntas.',
    'med.step.safe.0': 'Imagine um lugar onde você se sente completamente seguro — real ou imaginado. Olhe devagar: a luz, a hora do dia, o que você ouve, o que sente contra a pele.',
    'med.step.safe.1': 'Encontre o ponto aqui onde você mais gostaria de descansar, e vá até lá. Nada é exigido de você. Nada alcança você que você não permita.',
    'med.step.mtn.0': 'Imagine uma montanha — sua base larga, suas encostas firmes, seu cume imóvel. Deixe seu corpo e a montanha se tornarem a mesma forma: o assento como base, a coluna como encosta, a cabeça como cume.',
    'med.step.mtn.1': 'O tempo vai e vem ao redor da montanha — luz, nuvem, vento, tempestade. Seus pensamentos e humores são o tempo. A montanha não discute com ele, e não fica menor por causa dele.',
    'med.step.open.0': 'Solte a âncora da respiração. Deixe a atenção bem aberta, não em nada em particular. Sons, sensações, pensamentos surgem e passam — você não os persegue nem os afasta.',
    'med.step.open.1': 'Note que a consciência em si não se move. As coisas acontecem dentro dela, como as nuvens acontecem dentro do céu. Descanse como esse céu — nada a acrescentar, nada a remover.',
    'med.step.morn.0': 'Três respirações mais cheias, um pouco mais fundas que o normal — deixe-as acordar o corpo por dentro. Gire os ombros para trás uma vez e sinta a frente do corpo se abrir.',
    'med.step.morn.1': 'Traga o dia que vem à mente, sem apertar, depois escolha uma intenção — não uma tarefa, um jeito de ser. Paciente. Honesto. Corajoso. Gentil. Diga uma vez: hoje, serei ___.',
    'med.step.eve.0': 'Deixe o dia passar leve, como a paisagem pela janela de um trem — manhã, meio-dia, noite. Não pare em nada. Se um momento puxar, anote e diga: agora não.',
    'med.step.eve.1': 'Encontre um momento pelo qual você está contente que aconteceu, e uma coisa que você fez tão bem quanto pôde. Que isso baste. Agora solte o dia inteiro — está completo simplesmente porque acabou.',
    'med.step.nidra.0': 'Deite-se completamente imóvel — mais imóvel do que parece natural, só a respiração se move. Defina uma intenção breve, uma única frase calma no presente. Diga-a por dentro três vezes.',
    'med.step.nidra.1': 'Leve a atenção a cada ponto conforme é nomeado, sem se mexer — mão direita: polegar, dedos, palma, punho, antebraço, cotovelo, ombro. Depois o mesmo à esquerda.',
    'med.step.nidra.2': 'Ambos os quadris. Perna direita — coxa, joelho, canela, tornozelo, pé, dedos. Perna esquerda igual. Todas as costas contra o chão, o ventre subindo e descendo, o peito, a garganta.',
    'med.step.nidra.3': 'O rosto — mandíbula, lábios, nariz, bochechas, olhos, o espaço entre as sobrancelhas, o couro cabeludo. Agora o corpo inteiro de uma vez, brilhando de leve, sustentado pelo chão. Volte à sua intenção.',
    'med.step.chakra.root.0': 'Leve sua atenção à base da coluna, onde você encontra o chão. Este é o seu centro raiz — ele guarda seu senso de segurança, de ter o suficiente, de ter permissão para simplesmente estar aqui. Se hoje tem parecido instável, essa estabilidade começa bem aqui.',
    'med.step.chakra.root.1': 'Respire como se a própria respiração alcançasse bem no fundo. Em silêncio, no ritmo da respiração: Estou seguro. Estou aqui. Tenho o que preciso.',
    'med.step.chakra.sacral.0': 'Leve sua atenção ao baixo-ventre, uma palma abaixo do umbigo. Este é o seu centro sacral — ele guarda sua capacidade de sentir, de aproveitar, de deixar a vida se mover em vez de travar diante dela.',
    'med.step.chakra.sacral.1': 'Deixe a respiração suavizar esse espaço em vez de apertá-lo. Em silêncio, no ritmo da respiração: Deixo a vida se mover através de mim.',
    'med.step.chakra.solar-plexus.0': 'Leve sua atenção ao ponto macio sob as costelas. Este é o seu plexo solar — seu fogo, sua vontade, a parte de você que decide e age em vez de encolher.',
    'med.step.chakra.solar-plexus.1': 'Deixe a respiração avivá-lo com suavidade, sem forçar. Em silêncio, no ritmo da respiração: Confio no meu fogo.',
    'med.step.chakra.heart.0': 'Leve sua atenção ao centro do peito. Este é o seu centro do coração — o que permite dar sem se perder, e receber sem se proteger.',
    'med.step.chakra.heart.1': 'Deixe a respiração alargar esse espaço, à frente e atrás. Em silêncio, no ritmo da respiração: Dou e recebo amor livremente.',
    'med.step.chakra.throat.0': 'Leve sua atenção à cova da garganta. Esta é a sua voz — o que permite dizer a coisa verdadeira em vez da fácil.',
    'med.step.chakra.throat.1': 'Deixe a respiração passar por aqui sem obstáculos. Em silêncio, no ritmo da respiração: Digo minha verdade com facilidade.',
    'med.step.chakra.third-eye.0': 'Leve sua atenção ao espaço entre as sobrancelhas. É aqui que você sente o que sabe antes de conseguir explicar.',
    'med.step.chakra.third-eye.1': 'Deixe a respiração assentar o ruído para que esse saber mais silencioso possa ser ouvido. Em silêncio, no ritmo da respiração: Confio no que vejo por dentro.',
    'med.step.chakra.crown.0': 'Leve sua atenção ao topo da cabeça, e um pouco acima. É aqui que você se conecta com algo maior que as preocupações de hoje.',
    'med.step.chakra.crown.1': 'Deixe a respiração subir suavemente por todo o corpo até alcançá-lo. Em silêncio, no ritmo da respiração: Sou parte de algo vasto, e isso me sustenta.',
  },
  es: {
    'med.step.settle': 'Ojos cerrados. Deja que el cuerpo se asiente y la respiración se frene por sí sola.',
    'med.step.breath': 'Apoya la atención en la respiración — síguela al entrar, síguela al salir. Cuando la mente divague, ese darte cuenta es la práctica. Vuelve, con suavidad.',
    'med.step.close': 'Suelta la práctica. Nota cómo te sientes ahora, antes de abrir los ojos.',
    'med.step.ba.count': 'Ahora cuenta cada exhalación — del uno al diez, luego empieza de nuevo. Si pierdes la cuenta, simplemente empieza en uno. Nadie lleva un marcador.',
    'med.step.scan.0': 'Recorre la atención lentamente desde las plantas de los pies hacia arriba — tobillos, piernas, caderas, vientre, espalda, pecho, brazos, manos. Descansa unas respiraciones donde encuentres tensión, y deja que se ablande.',
    'med.step.scan.1': 'Ahora los hombros, la garganta, la mandíbula, el espacio alrededor de los ojos, el cuero cabelludo. Luego siente todo el cuerpo a la vez — pesado, cálido, respirando por sí solo.',
    'med.step.metta.0': 'Tráete a la mente, tal como estás hoy. En silencio ofrece: que esté a salvo, que esté bien, que esté en paz. Repítelo despacio y permítete decirlo en serio.',
    'med.step.metta.1': 'Trae a la mente a alguien a quien quieres con facilidad. Imagina su cara y ofrécele lo mismo: que estés a salvo, que estés bien, que estés en paz.',
    'med.step.metta.2': 'Ahora amplíalo — alguien que apenas conoces, alguien que te resulta difícil, luego todos, en todas partes: que todos los seres estén a salvo, que todos los seres estén en paz.',
    'med.step.bath.0': 'Deja que el tono pase a primer plano. No escuchas con esfuerzo — dejas que el sonido llegue, como llega la luz.',
    'med.step.bath.1': 'Nota en qué parte del cuerpo parece posarse el sonido — el pecho, el cráneo, las manos. Deja que el espacio entre tú y el sonido se disuelva.',
    'med.step.grat.0': 'Trae a la mente una cosa del último día que fue bien, por pequeña que sea. No solo la nombres — siente dónde se asienta el agradecimiento en el cuerpo.',
    'med.step.grat.1': 'Ahora algo que sueles dar por sentado — un cuerpo que funciona, un techo, alguien que se quedó. Quédate con ello unas respiraciones.',
    'med.step.grat.2': 'Una más — algo sobre ti. Una manera en que estuviste presente, algo que manejaste, un esfuerzo que nadie vio. Sostén las tres juntas.',
    'med.step.safe.0': 'Imagina un lugar donde te sientes completamente a salvo — real o imaginado. Míralo despacio: la luz, la hora del día, lo que oyes, lo que sientes contra la piel.',
    'med.step.safe.1': 'Encuentra el sitio aquí donde más querrías descansar, y ve allí. Nada se te exige. Nada te alcanza que tú no permitas.',
    'med.step.mtn.0': 'Imagina una montaña — su base ancha, sus laderas firmes, su cima quieta. Deja que tu cuerpo y la montaña sean la misma forma: el asiento como base, la columna como ladera, la cabeza como cumbre.',
    'med.step.mtn.1': 'El clima viene y va alrededor de la montaña — luz, nube, viento, tormenta. Tus pensamientos y estados de ánimo son el clima. La montaña no discute con él, y no queda disminuida por él.',
    'med.step.open.0': 'Suelta el ancla de la respiración. Deja que la atención esté bien abierta, no en nada en particular. Sonidos, sensaciones, pensamientos surgen y pasan — ni los persigues ni los apartas.',
    'med.step.open.1': 'Nota que la conciencia misma no se mueve. Las cosas ocurren dentro de ella, como las nubes ocurren dentro del cielo. Descansa como ese cielo — nada que añadir, nada que quitar.',
    'med.step.morn.0': 'Tres respiraciones más plenas, un poco más profundas de lo normal — deja que despierten el cuerpo desde dentro. Gira los hombros hacia atrás una vez y siente cómo se abre el frente del cuerpo.',
    'med.step.morn.1': 'Trae a la mente el día que viene, sin apretar, luego elige una intención — no una tarea, una manera de ser. Paciente. Honesto. Valiente. Amable. Dilo una vez: hoy seré ___.',
    'med.step.eve.0': 'Deja que el día se repase con ligereza, como el paisaje desde la ventana de un tren — mañana, mediodía, noche. No te detengas en nada. Si un momento tira, anótalo y di: ahora no.',
    'med.step.eve.1': 'Encuentra un momento del que te alegras de que ocurriera, y una cosa que hiciste tan bien como pudiste. Que eso baste. Ahora suelta el día entero — está completo simplemente porque ha terminado.',
    'med.step.nidra.0': 'Túmbate completamente quieto — más quieto de lo que parece natural, solo la respiración se mueve. Fija una intención breve, una única frase serena en presente. Dila por dentro tres veces.',
    'med.step.nidra.1': 'Lleva la atención a cada lugar según se nombra, sin moverte — mano derecha: pulgar, dedos, palma, muñeca, antebrazo, codo, hombro. Luego lo mismo a la izquierda.',
    'med.step.nidra.2': 'Ambas caderas. Pierna derecha — muslo, rodilla, espinilla, tobillo, pie, dedos. Pierna izquierda igual. Toda la espalda contra el suelo, el vientre subiendo y bajando, el pecho, la garganta.',
    'med.step.nidra.3': 'La cara — mandíbula, labios, nariz, mejillas, ojos, el espacio entre las cejas, el cuero cabelludo. Ahora todo el cuerpo a la vez, brillando tenue, sostenido por el suelo. Vuelve a tu intención.',
    'med.step.chakra.root.0': 'Lleva tu atención a la base de tu columna, donde te encuentras con el suelo. Este es tu centro raíz — sostiene tu sentido de seguridad, de tener suficiente, de tener permiso para simplemente estar aquí. Si hoy se ha sentido inestable, esa estabilidad empieza justo aquí.',
    'med.step.chakra.root.1': 'Respira como si la respiración misma llegara hasta el fondo. En silencio, al ritmo de la respiración: Estoy a salvo. Estoy aquí. Tengo lo que necesito.',
    'med.step.chakra.sacral.0': 'Lleva tu atención a tu bajo vientre, a un palmo por debajo del ombligo. Este es tu centro sacro — sostiene tu capacidad de sentir, de disfrutar, de dejar que la vida se mueva en vez de congelarte ante ella.',
    'med.step.chakra.sacral.1': 'Deja que la respiración suavice este espacio en vez de tensarlo. En silencio, al ritmo de la respiración: Dejo que la vida se mueva a través de mí.',
    'med.step.chakra.solar-plexus.0': 'Lleva tu atención al lugar blando bajo tus costillas. Este es tu plexo solar — tu fuego, tu voluntad, la parte de ti que decide y actúa en vez de encogerse.',
    'med.step.chakra.solar-plexus.1': 'Deja que la respiración lo avive con suavidad, sin forzarlo. En silencio, al ritmo de la respiración: Confío en mi propio fuego.',
    'med.step.chakra.heart.0': 'Lleva tu atención al centro de tu pecho. Este es tu centro del corazón — lo que te permite dar sin perderte a ti mismo, y recibir sin protegerte.',
    'med.step.chakra.heart.1': 'Deja que la respiración ensanche este espacio, por delante y por detrás. En silencio, al ritmo de la respiración: Doy y recibo amor libremente.',
    'med.step.chakra.throat.0': 'Lleva tu atención al hueco de tu garganta. Esta es tu voz — lo que te permite decir lo verdadero en vez de lo fácil.',
    'med.step.chakra.throat.1': 'Deja que la respiración pase por aquí sin obstáculos. En silencio, al ritmo de la respiración: Digo mi verdad con soltura.',
    'med.step.chakra.third-eye.0': 'Lleva tu atención al espacio entre tus cejas. Aquí es donde sientes lo que sabes antes de poder explicarlo.',
    'med.step.chakra.third-eye.1': 'Deja que la respiración calme el ruido para que se pueda escuchar ese saber más silencioso. En silencio, al ritmo de la respiración: Confío en lo que veo por dentro.',
    'med.step.chakra.crown.0': 'Lleva tu atención a la coronilla de tu cabeza, y un poco por encima. Aquí es donde te conectas con algo más grande que las preocupaciones de hoy.',
    'med.step.chakra.crown.1': 'Deja que la respiración se eleve suavemente por todo el cuerpo hasta encontrarlo. En silencio, al ritmo de la respiración: Soy parte de algo vasto, y me sostiene.',
  },
  de: {
    'med.step.settle': 'Augen geschlossen. Lass den Körper sich setzen und den Atem von selbst langsamer werden.',
    'med.step.breath': 'Leg die Aufmerksamkeit auf den Atem — folge ihm hinein, folge ihm hinaus. Wenn der Geist abschweift, ist dieses Bemerken die Praxis. Komm sanft zurück.',
    'med.step.close': 'Lass die Praxis los. Bemerke, wie du dich jetzt fühlst, bevor du die Augen öffnest.',
    'med.step.ba.count': 'Zähl jetzt jede Ausatmung — eins bis zehn, dann fang von vorn an. Verlierst du die Zählung, beginn einfach bei eins. Niemand führt Buch.',
    'med.step.scan.0': 'Führe die Aufmerksamkeit langsam von den Fußsohlen aufwärts — Knöchel, Beine, Hüften, Bauch, Rücken, Brust, Arme, Hände. Bleib ein paar Atemzüge, wo du Spannung triffst, und lass sie weich werden.',
    'med.step.scan.1': 'Jetzt die Schultern, die Kehle, den Kiefer, den Raum um die Augen, die Kopfhaut. Dann spür den ganzen Körper auf einmal — schwer, warm, von selbst atmend.',
    'med.step.metta.0': 'Bring dich in den Sinn, genau so, wie du heute bist. Biete still an: möge ich sicher sein, möge es mir gut gehen, möge ich in Frieden sein. Wiederhol es langsam und erlaube dir, es wirklich zu meinen.',
    'med.step.metta.1': 'Bring jemanden in den Sinn, den du leicht liebst. Stell dir sein Gesicht vor und biete dasselbe an: mögest du sicher sein, möge es dir gut gehen, mögest du in Frieden sein.',
    'med.step.metta.2': 'Jetzt weite es aus — jemand, den du kaum kennst, jemand, den du schwierig findest, dann alle, überall: mögen alle Wesen sicher sein, mögen alle Wesen in Frieden sein.',
    'med.step.bath.0': 'Lass den Ton in den Vordergrund kommen. Du hörst nicht angestrengt hin — du lässt den Klang ankommen, so wie Licht ankommt.',
    'med.step.bath.1': 'Bemerke, wo im Körper der Klang zu landen scheint — die Brust, der Schädel, die Hände. Lass den Raum zwischen dir und dem Klang sich auflösen.',
    'med.step.grat.0': 'Bring eine Sache aus dem letzten Tag in den Sinn, die gut lief, so klein sie auch war. Benenn sie nicht nur — spür, wo die Dankbarkeit im Körper sitzt.',
    'med.step.grat.1': 'Jetzt etwas, das du sonst für selbstverständlich hältst — ein funktionierender Körper, ein Dach, jemand, der geblieben ist. Bleib ein paar Atemzüge dabei.',
    'med.step.grat.2': 'Noch eine — etwas über dich selbst. Eine Art, wie du da warst, eine Sache, die du gemeistert hast, eine Mühe, die niemand gesehen hat. Halt alle drei zusammen.',
    'med.step.safe.0': 'Stell dir einen Ort vor, an dem du dich völlig sicher fühlst — echt oder erdacht. Sieh dich langsam um: das Licht, die Tageszeit, was du hörst, was du auf der Haut spürst.',
    'med.step.safe.1': 'Finde die Stelle hier, an der du am liebsten ruhen würdest, und geh dorthin. Nichts wird von dir verlangt. Nichts erreicht dich, das du nicht zulässt.',
    'med.step.mtn.0': 'Stell dir einen Berg vor — seine breite Basis, seine festen Flanken, seinen stillen Gipfel. Lass deinen Körper und den Berg dieselbe Form werden: der Sitz als Basis, die Wirbelsäule als Hang, der Kopf als Gipfel.',
    'med.step.mtn.1': 'Das Wetter kommt und geht um den Berg — Licht, Wolke, Wind, Sturm. Deine Gedanken und Stimmungen sind das Wetter. Der Berg streitet nicht mit ihm, und es macht ihn nicht kleiner.',
    'med.step.open.0': 'Lass den Anker des Atems los. Lass die Aufmerksamkeit weit offen sein, nicht auf etwas Bestimmtem. Geräusche, Empfindungen, Gedanken steigen auf und vergehen — du jagst ihnen nicht nach und schiebst sie nicht weg.',
    'med.step.open.1': 'Bemerke, dass das Gewahrsein selbst sich nicht bewegt. Die Dinge geschehen darin, wie Wolken im Himmel geschehen. Ruh als dieser Himmel — nichts hinzuzufügen, nichts wegzunehmen.',
    'med.step.morn.0': 'Drei vollere Atemzüge, etwas tiefer als sonst — lass sie den Körper von innen wecken. Roll die Schultern einmal nach hinten und spür, wie sich die Vorderseite des Körpers öffnet.',
    'med.step.morn.1': 'Bring den kommenden Tag locker in den Sinn, dann wähl eine Absicht — keine Aufgabe, eine Art zu sein. Geduldig. Ehrlich. Mutig. Freundlich. Sag es einmal: heute werde ich ___ sein.',
    'med.step.eve.0': 'Lass den Tag leicht vorüberziehen, wie Landschaft aus dem Zugfenster — Morgen, Mittag, Abend. Bleib an nichts hängen. Wenn ein Moment zieht, notier ihn und sag: nicht jetzt.',
    'med.step.eve.1': 'Finde einen Moment, über den du froh bist, dass er geschah, und eine Sache, die du so gut gemacht hast, wie du konntest. Lass das genug sein. Jetzt lass den ganzen Tag los — er ist vollständig, einfach weil er vorbei ist.',
    'med.step.nidra.0': 'Leg dich völlig still hin — stiller, als sich natürlich anfühlt, nur der Atem bewegt sich. Setz eine kurze Absicht, einen einzigen ruhigen Satz im Präsens. Sag ihn dreimal innerlich.',
    'med.step.nidra.1': 'Bring die Aufmerksamkeit zu jeder Stelle, sowie sie genannt wird, ohne dich zu bewegen — rechte Hand: Daumen, Finger, Handfläche, Handgelenk, Unterarm, Ellbogen, Schulter. Dann dasselbe links.',
    'med.step.nidra.2': 'Beide Hüften. Rechtes Bein — Oberschenkel, Knie, Schienbein, Knöchel, Fuß, Zehen. Linkes Bein genauso. Der ganze Rücken am Boden, der Bauch, der sich hebt und senkt, die Brust, die Kehle.',
    'med.step.nidra.3': 'Das Gesicht — Kiefer, Lippen, Nase, Wangen, Augen, der Raum zwischen den Brauen, die Kopfhaut. Jetzt der ganze Körper auf einmal, schwach leuchtend, vom Boden gehalten. Kehr zu deiner Absicht zurück.',
    'med.step.chakra.root.0': 'Bring deine Aufmerksamkeit zur Basis der Wirbelsäule, wo du den Boden triffst. Das ist dein Wurzelzentrum — es trägt dein Gefühl von Sicherheit, von Genug-Haben, von dem Recht, einfach hier zu sein. Wenn sich der heutige Tag wacklig angefühlt hat, beginnt diese Standfestigkeit genau hier.',
    'med.step.chakra.root.1': 'Atme, als würde der Atem selbst ganz nach unten reichen. Still, im Takt des Atems: Ich bin sicher. Ich bin hier. Ich habe, was ich brauche.',
    'med.step.chakra.sacral.0': 'Bring deine Aufmerksamkeit zum Unterbauch, eine Handbreit unter dem Nabel. Das ist dein Sakralzentrum — es trägt deine Fähigkeit zu fühlen, zu genießen, das Leben fließen zu lassen, statt davor zu erstarren.',
    'med.step.chakra.sacral.1': 'Lass den Atem diesen Raum weich machen, statt ihn zu verengen. Still, im Takt des Atems: Ich lasse das Leben durch mich hindurchfließen.',
    'med.step.chakra.solar-plexus.0': 'Bring deine Aufmerksamkeit zur weichen Stelle unter den Rippen. Das ist dein Solarplexus — dein Feuer, dein Wille, der Teil von dir, der entscheidet und handelt, statt sich zurückzuziehen.',
    'med.step.chakra.solar-plexus.1': 'Lass den Atem es sanft anfachen, ohne es zu erzwingen. Still, im Takt des Atems: Ich vertraue meinem Feuer.',
    'med.step.chakra.heart.0': 'Bring deine Aufmerksamkeit zur Mitte der Brust. Das ist dein Herzzentrum — es lässt dich geben, ohne dich zu verlieren, und empfangen, ohne dich zu schützen.',
    'med.step.chakra.heart.1': 'Lass den Atem diesen Raum weiten, vorne und hinten. Still, im Takt des Atems: Ich gebe und empfange Liebe frei.',
    'med.step.chakra.throat.0': 'Bring deine Aufmerksamkeit zur Kuhle der Kehle. Das ist deine Stimme — sie lässt dich das Wahre sagen statt des Einfachen.',
    'med.step.chakra.throat.1': 'Lass den Atem hier ungehindert hindurchziehen. Still, im Takt des Atems: Ich sage meine Wahrheit mit Leichtigkeit.',
    'med.step.chakra.third-eye.0': 'Bring deine Aufmerksamkeit zum Raum zwischen den Augenbrauen. Hier spürst du, was du weißt, bevor du es erklären kannst.',
    'med.step.chakra.third-eye.1': 'Lass den Atem den Lärm zur Ruhe bringen, damit dieses leisere Wissen gehört werden kann. Still, im Takt des Atems: Ich vertraue dem, was ich in mir sehe.',
    'med.step.chakra.crown.0': 'Bring deine Aufmerksamkeit zum Scheitel des Kopfes, und ein Stück darüber. Hier verbindest du dich mit etwas Größerem als den Sorgen von heute.',
    'med.step.chakra.crown.1': 'Lass den Atem sanft durch den ganzen Körper aufsteigen, um es zu erreichen. Still, im Takt des Atems: Ich bin Teil von etwas Weitem, und es trägt mich.',
  },
  fr: {
    'med.step.settle': 'Yeux fermés. Laisse le corps se poser et le souffle ralentir de lui-même.',
    'med.step.breath': 'Pose ton attention sur le souffle — suis-le à l’entrée, suis-le à la sortie. Quand l’esprit s’égare, ce constat est la pratique. Reviens, doucement.',
    'med.step.close': 'Laisse la pratique partir. Remarque comment tu te sens maintenant, avant d’ouvrir les yeux.',
    'med.step.ba.count': 'Maintenant compte chaque expiration — de un à dix, puis recommence. Si tu perds le compte, repars simplement à un. Personne ne tient les scores.',
    'med.step.scan.0': 'Balaie ton attention lentement depuis la plante des pieds vers le haut — chevilles, jambes, hanches, ventre, dos, poitrine, bras, mains. Reste quelques souffles là où tu rencontres une tension, et laisse-la s’adoucir.',
    'med.step.scan.1': 'Maintenant les épaules, la gorge, la mâchoire, l’espace autour des yeux, le cuir chevelu. Puis sens tout le corps d’un coup — lourd, chaud, respirant tout seul.',
    'med.step.metta.0': 'Amène-toi à l’esprit, tel que tu es aujourd’hui. En silence, offre : que je sois en sécurité, que je sois bien, que je sois en paix. Répète-le lentement et permets-toi de le penser vraiment.',
    'med.step.metta.1': 'Amène à l’esprit quelqu’un que tu aimes facilement. Imagine son visage et offre-lui la même chose : que tu sois en sécurité, que tu sois bien, que tu sois en paix.',
    'med.step.metta.2': 'Maintenant élargis — quelqu’un que tu connais à peine, quelqu’un que tu trouves difficile, puis tout le monde, partout : que tous les êtres soient en sécurité, que tous les êtres soient en paix.',
    'med.step.bath.0': 'Laisse le son passer au premier plan. Tu n’écoutes pas avec effort — tu laisses le son arriver, comme la lumière arrive.',
    'med.step.bath.1': 'Remarque à quel endroit du corps le son semble se poser — la poitrine, le crâne, les mains. Laisse l’espace entre toi et le son se dissoudre.',
    'med.step.grat.0': 'Amène à l’esprit une chose du dernier jour qui s’est bien passée, si petite soit-elle. Ne te contente pas de la nommer — sens où la gratitude se pose dans le corps.',
    'med.step.grat.1': 'Maintenant quelque chose que tu tiens d’habitude pour acquis — un corps qui fonctionne, un toit, quelqu’un qui est resté. Reste-y quelques souffles.',
    'med.step.grat.2': 'Une de plus — quelque chose sur toi. Une façon dont tu as été présent, une chose que tu as gérée, un effort que personne n’a vu. Tiens les trois ensemble.',
    'med.step.safe.0': 'Imagine un lieu où tu te sens complètement en sécurité — réel ou imaginé. Regarde-le lentement : la lumière, l’heure du jour, ce que tu entends, ce que tu sens contre la peau.',
    'med.step.safe.1': 'Trouve l’endroit ici où tu voudrais le plus te reposer, et vas-y. Rien ne t’est demandé. Rien ne t’atteint que tu ne permettes.',
    'med.step.mtn.0': 'Imagine une montagne — sa large base, ses flancs solides, son sommet immobile. Laisse ton corps et la montagne devenir la même forme : l’assise comme base, la colonne comme versant, la tête comme sommet.',
    'med.step.mtn.1': 'Le temps va et vient autour de la montagne — lumière, nuage, vent, tempête. Tes pensées et tes humeurs sont le temps. La montagne ne discute pas avec lui, et il ne la diminue pas.',
    'med.step.open.0': 'Laisse partir l’ancre du souffle. Laisse l’attention grande ouverte, sur rien en particulier. Sons, sensations, pensées surgissent et passent — tu ne les poursuis pas et tu ne les repousses pas.',
    'med.step.open.1': 'Remarque que la conscience elle-même ne bouge pas. Les choses se produisent en elle, comme les nuages se produisent dans le ciel. Repose comme ce ciel — rien à ajouter, rien à retirer.',
    'med.step.morn.0': 'Trois souffles plus amples, un peu plus profonds que d’habitude — laisse-les réveiller le corps de l’intérieur. Roule les épaules en arrière une fois et sens l’avant du corps s’ouvrir.',
    'med.step.morn.1': 'Amène la journée à venir à l’esprit, sans serrer, puis choisis une intention — pas une tâche, une manière d’être. Patient. Honnête. Courageux. Bienveillant. Dis-le une fois : aujourd’hui, je serai ___.',
    'med.step.eve.0': 'Laisse la journée défiler légèrement, comme le paysage par la fenêtre d’un train — matin, midi, soir. Ne t’arrête sur rien. Si un moment tire, note-le et dis : pas maintenant.',
    'med.step.eve.1': 'Trouve un moment dont tu es content qu’il soit arrivé, et une chose que tu as faite aussi bien que possible. Que cela suffise. Maintenant laisse partir la journée entière — elle est complète simplement parce qu’elle est finie.',
    'med.step.nidra.0': 'Allonge-toi complètement immobile — plus immobile qu’il ne paraît naturel, seul le souffle bouge. Pose une brève intention, une seule phrase calme au présent. Dis-la intérieurement trois fois.',
    'med.step.nidra.1': 'Porte l’attention à chaque endroit à mesure qu’il est nommé, sans bouger — main droite : pouce, doigts, paume, poignet, avant-bras, coude, épaule. Puis la même chose à gauche.',
    'med.step.nidra.2': 'Les deux hanches. Jambe droite — cuisse, genou, tibia, cheville, pied, orteils. Jambe gauche pareil. Tout le dos contre le sol, le ventre qui monte et descend, la poitrine, la gorge.',
    'med.step.nidra.3': 'Le visage — mâchoire, lèvres, nez, joues, yeux, l’espace entre les sourcils, le cuir chevelu. Maintenant tout le corps d’un coup, luisant faiblement, tenu par le sol. Reviens à ton intention.',
    'med.step.chakra.root.0': 'Porte ton attention à la base de la colonne, là où tu rencontres le sol. C’est ton centre racine — il porte ton sentiment de sécurité, d’avoir assez, d’avoir le droit d’être simplement ici. Si aujourd’hui a semblé instable, cette stabilité commence ici même.',
    'med.step.chakra.root.1': 'Respire comme si le souffle lui-même atteignait tout en bas. En silence, au rythme du souffle : Je suis en sécurité. Je suis ici. J’ai ce qu’il me faut.',
    'med.step.chakra.sacral.0': 'Porte ton attention au bas-ventre, une paume sous le nombril. C’est ton centre sacré — il porte ta capacité à ressentir, à savourer, à laisser la vie circuler plutôt que de te figer.',
    'med.step.chakra.sacral.1': 'Laisse le souffle adoucir cet espace plutôt que de le serrer. En silence, au rythme du souffle : Je laisse la vie se mouvoir à travers moi.',
    'med.step.chakra.solar-plexus.0': 'Porte ton attention au point tendre sous les côtes. C’est ton plexus solaire — ton feu, ta volonté, la part de toi qui décide et agit plutôt que de se rétracter.',
    'med.step.chakra.solar-plexus.1': 'Laisse le souffle l’attiser doucement, sans le forcer. En silence, au rythme du souffle : Je fais confiance à mon feu.',
    'med.step.chakra.heart.0': 'Porte ton attention au centre de la poitrine. C’est ton centre du cœur — ce qui te permet de donner sans te perdre, et de recevoir sans te protéger.',
    'med.step.chakra.heart.1': 'Laisse le souffle élargir cet espace, devant et derrière. En silence, au rythme du souffle : Je donne et je reçois de l’amour librement.',
    'med.step.chakra.throat.0': 'Porte ton attention au creux de la gorge. C’est ta voix — ce qui te permet de dire la chose vraie plutôt que la chose facile.',
    'med.step.chakra.throat.1': 'Laisse le souffle passer ici sans obstacle. En silence, au rythme du souffle : Je dis ma vérité avec aisance.',
    'med.step.chakra.third-eye.0': 'Porte ton attention à l’espace entre les sourcils. C’est là que tu sens ce que tu sais avant de pouvoir l’expliquer.',
    'med.step.chakra.third-eye.1': 'Laisse le souffle apaiser le bruit pour que ce savoir plus silencieux puisse se faire entendre. En silence, au rythme du souffle : Je fais confiance à ce que je vois en moi.',
    'med.step.chakra.crown.0': 'Porte ton attention au sommet de la tête, et un peu au-dessus. C’est là que tu te relies à quelque chose de plus grand que les soucis d’aujourd’hui.',
    'med.step.chakra.crown.1': 'Laisse le souffle monter doucement à travers tout le corps pour le rejoindre. En silence, au rythme du souffle : Je fais partie de quelque chose de vaste, et cela me porte.',
  },
}

async function synthesize(text, langCode) {
  const res = await fetch('https://api.inworld.ai/tts/v1/voice', {
    method: 'POST',
    headers: {
      Authorization: `Basic ${API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      text,
      voiceId: VOICE_ID,
      modelId: MODEL_ID,
      audioConfig: { speakingRate: 0.9 },
      deliveryMode: 'BALANCED',
      language: langCode,
    }),
  })

  if (!res.ok) {
    const body = await res.text()
    throw new Error(`HTTP ${res.status}: ${body}`)
  }

  const json = await res.json()
  return Buffer.from(json.audioContent, 'base64')
}

async function main() {
  const completedLocales = []
  let stoppedEarly = false

  outer: for (const locale of LOCALES) {
    const dir = path.join(OUT_ROOT, locale)
    await mkdir(dir, { recursive: true })
    const lines = LINES[locale]
    const langCode = LANG_CODES[locale]

    for (const [key, text] of Object.entries(lines)) {
      process.stdout.write(`${locale}/${key}... `)
      try {
        const audio = await synthesize(text, langCode)
        await writeFile(path.join(dir, `${key}.mp3`), audio)
        console.log(`ok (${audio.length} bytes)`)
      } catch (err) {
        console.log('FAILED')
        console.error(`  ${err.message}`)
        stoppedEarly = true
        break outer
      }
    }
    completedLocales.push(locale)
  }

  console.log(`\nFully completed locales this run: ${completedLocales.join(', ') || '(none)'}`)
  if (stoppedEarly) console.log('Stopped early due to a failure.')
}

main()
